### ISSUE TITLE
Harvest Chat doesn't prompt for user names

### ISSUE THREAD

**Issue by mitalia** [chop-dbhi/harvest-site#47]
Not sure if HipChat changed the way they integrate, but the Harvest chat room no longer asks people for their names, and so it's hard to know who you are talking to in the chat room. Can it be modified to prompt for them?

**Comment by murphyke** [comment]
https://github.com/cbmi/harvest-site/blob/gh-pages/js/hipchat.js#L25 sets `anonymous` to 1 (default is 0).  I just edited it to be 0, thinking I would get a fork, but evidently I have commit access, so ... maybe this will fix it.

**Comment by bruth** [comment]
That did not seem to do anything. Where did you read about that flag toggling the behavior?

**Comment by bruth** [comment]
Looks like timezone needs to be set? http://help.hipchat.com/knowledgebase/articles/238941-how-do-i-embed-the-hipchat-web-client-

**Comment by murphyke** [comment]
Aha, I wasn't careful; I think it should actually be 'false', perhaps?  http://help.hipchat.com/knowledgebase/articles/238941-how-do-i-embed-the-hipchat-web-client

**Comment by murphyke** [comment]
(or not present)

**Comment by bruth** [comment]
Yea.. timezone is set. I will try unsetting it.

**Comment by bruth** [comment]
Changing to booleans didn't do anything.

**Comment by bruth** [comment]
Based on the options here.. which I presume is up-to-date, they removed the `anonymous` option: https://bitbucket.org/atlassianlabs/jquery-hipchat-plugin

**Comment by murphyke** [comment]
it looks like any occurrence of `anonymous=xxx` in the URL causes the login to be anonymous, but if `anonymous` does not occur in the URL, then the user is prompted for name

**Comment by bruth** [comment]
Tried that to no avail.

**Comment by murphyke** [comment]
@bruth Did the site get regenerated (and how, in general, do you know)?  http://harvest.research.chop.edu/js/hipchat.js  still has `anonymous: 1`

**Comment by bruth** [comment]
It rebuilds on http://dev.harvest.io

**Comment by gracecodes144** [comment]
http://dev.harvest.io/chat/ is allowing me to enter my name...

https://www.dropbox.com/s/0gi17tgp1f4dd0a/Screenshot%202014-03-06%2012.51.02.png

**Comment by bruth** [comment]
Great, looks like my Chrome session was cached. Confirmed it works in Firefox.

**Comment by bruth** [comment]
Pushed to production.
